# Generated by Django 3.2.12 on 2026-02-23 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('company_id', models.CharField(default='CHC002', max_length=20)),
                ('batch_number', models.CharField(max_length=20, unique=True)),
                ('batch_details', models.JSONField(default=list)),
                ('specimen_count', models.JSONField(default=list)),
                ('received', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('company_id', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField()),
                ('employee_id', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=50)),
                ('testdetails', models.JSONField(default=list)),
                ('netAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMode', models.CharField(default='Credit', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('established_year', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_company',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('company_id', models.CharField(default='', max_length=20)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('mode', models.CharField(default='Offsite', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('employee_id', models.CharField(max_length=50)),
                ('vitals', models.JSONField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('barcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('patient_history', models.CharField(blank=True, max_length=1200, null=True)),
                ('xray_notes', models.CharField(blank=True, max_length=5000, null=True)),
                ('xray_report', models.CharField(blank=True, max_length=5000, null=True)),
                ('ecg_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('pft_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('audiometry_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('xrayfilm_file', models.CharField(blank=True, max_length=200, null=True)),
                ('ecg_file', models.CharField(blank=True, max_length=200, null=True)),
                ('pft_file', models.CharField(blank=True, max_length=200, null=True)),
                ('audiometric_file', models.CharField(blank=True, max_length=200, null=True)),
                ('company_id', models.CharField(default='CHC002', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ophthalmology',
            fields=[
                ('barcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('visual_acuity', models.JSONField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient_complaints', models.CharField(blank=True, max_length=505)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('package_name', models.CharField(blank=True, max_length=100, null=True)),
                ('investigations', models.JSONField(blank=True, null=True)),
                ('totalAmount', models.CharField(max_length=100)),
                ('company_id', models.CharField(default='', max_length=20)),
                ('package_id', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('confirmPassword', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.CharField(default='CHC002', max_length=20)),
                ('barcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('testdetails', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
