# Generated by Django 3.2.12 on 2026-02-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeregistration',
            name='mode',
        ),
        migrations.AddField(
            model_name='billing',
            name='mode',
            field=models.CharField(default='Offsite', max_length=200),
        ),
    ]
