# Generated by Django 3.2.12 on 2026-02-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260223_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ophthalmology',
        ),
        migrations.AddField(
            model_name='investigation',
            name='ophthalmology_patient_complaints',
            field=models.CharField(blank=True, max_length=505, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='ophthalmology_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='visual_acuity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='mode',
            field=models.CharField(default='Onsite', max_length=200),
        ),
    ]
