# Generated by Django 3.2.12 on 2026-03-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260227_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='audiometric_file',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='audiometry_notes',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='ecg_file',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='ecg_notes',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='ophthalmology_patient_complaints',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='ophthalmology_remarks',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='pft_file',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='pft_notes',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='visual_acuity',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='xray_notes',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='xray_report',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='xrayfilm_file',
        ),
        migrations.AddField(
            model_name='investigation',
            name='audiometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='ecg',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='ophthalmology',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='pft',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='xray',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
