# Generated by Django 3.2.12 on 2026-03-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260302_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHCtest',
            fields=[
                ('test_name', models.CharField(max_length=100)),
                ('test_price', models.CharField(max_length=100)),
                ('test_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fileuploaded', models.BooleanField(default=False)),
                ('is_notes', models.BooleanField(default=False)),
                ('is_report', models.BooleanField(default=False)),
            ],
        ),
    ]
