# Generated by Django 3.2 on 2026-03-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chctest'),
    ]

    operations = [
        migrations.CreateModel(
            name='unregisteredEmployee',
            fields=[
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_id', models.CharField(max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='billing',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employeeregistration',
            name='id',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='age',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='audiometry',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='ecg',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='ophthalmology',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='pft',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='xray',
        ),
        migrations.AddField(
            model_name='billing',
            name='chctestdetails',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='billing',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chctest',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chctest',
            name='report',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='barcode',
            field=models.CharField(default='TEMP', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='employee_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='test_results',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='barcode',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
