# Generated by Django 3.2 on 2026-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employeetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unregisteredemployee',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
    ]
