# Generated by Django 3.2 on 2026-03-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20260330_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unregisteredemployee',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
