# Generated by Django 3.2 on 2026-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20260331_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='gender',
            field=models.CharField(default='Common', max_length=20),
        ),
    ]
