# Generated by Django 3.2 on 2026-05-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_package_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnInvestigation',
            fields=[
                ('test_name', models.CharField(max_length=100)),
                ('test_price', models.CharField(max_length=100)),
                ('test_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicInvestigationFields',
            fields=[
                ('field_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('field_name', models.CharField(max_length=100)),
                ('field_values', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationChecklist',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('company_id', models.CharField(max_length=20)),
                ('checklist', models.JSONField(default=list)),
                ('vitals', models.JSONField(default=list)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='addon_investigation',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='billing',
            name='dynamic_fields',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='billing',
            name='extra_barcode',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='billing',
            name='package_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='investigation',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='addon_investigation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='extra_barcode',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='sample',
            name='package_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
