# Generated by Django 3.2 on 2026-04-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_package_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='package_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='package_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
