# Generated by Django 3.2 on 2026-06-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260401_1723'),
        ('core', '0011_auto_20260515_1648'),
    ]

    operations = [
    ]
